<?php
/**
 * Lightweight and simple homepage (that needs updated!).
 */

$tabIndex = 3;

echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <title>Joshua Ross</title>
        <meta name="keywords" content="Joshua Ross, Joshua L Ross, Josh Ross, joshuaross, joshross, jross, joshualross, Resume, Projects, python, Python, go, PHP, php, web developer, web engineer, engineer, PHP Web Developer, php web developer, zend certified, frontend engineer, JavaScript, jQuery, backbone"/>
        <meta name="description" content="Information about Joshua Ross including resume and projects"/>
        <meta name="author" content="Joshua Ross"/>
        <meta name="revised" content="Joshua Ross, <?php echo date('d-m-Y');?>"/>
        <meta http-equiv="Content-Language" content="en"/>
        <meta name="language" content="en"/>
        <link rel="stylesheet" type="text/css" href="/public/css/style.css"/>
        <script type="text/javascript"><!--
        var tabIndex=0;
        function email(user, host) {
            e = user + '@';
            for (i = 0; i < host.length - 1; i++) { e = e + host[i] + '.'; }
            e = e + host[host.length - 1] ;
            document.writeln('<a href="mailto:' + e + '" title="' + e + '" tabindex="' + tabIndex++ + '">' + e + '</a>');
        }//-->
        </script>
		<script type="text/javascript">var a=new Date,b=a.getHours()+a.getTimezoneOffset()/60;if(18==a.getDate()&&0==a.getMonth()&&2012==a.getFullYear()&&13<=b&&24>=b)window.location="http://sopastrike.com/strike";</script>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-24269912-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
    </head>
    <body>
        <header>
            <h1>Joshua Ross</h1>
	    <h4>
                <script type="text/javascript">email('joshualross', [ 'gmail', 'com' ]);</script>
                <noscript><address>joshualross at gmail dot com</address></noscript>
            </h4>
            <h4>
                <address><a href="https://www.linkedin.com/in/joshualross" title="Joshua's LinkedIn Profile">LinkedIn Profile</a>
            </h4>
        </header>
        <section>
            <article>
                <h3>About</h3>
                <p>
                    I am an engineer with a strong focus in web development.  Currently working for 
                    <a href="http://www.uber.com/" title="Uber" tabindex="<?php echo $tabIndex++; ?>">Uber</a>,
                    my primary experience lies in building web applications in python and php.
                    <!--<a href="http://www.zend.com/store/education/certification/yellow-pages.php#show-ClientCandidateID=ZEND005972" title="My Zend PHP5 Certification" tabindex="<?php echo $tabIndex++; ?>">
                    	Zend PHP5 Certified
                    </a>-->
                </p>
                <p>
                    I enjoy developing backend components as much as frontend, and have many years experience with both.
                    I've worked python and most recently go at Uber.
                    I am very detail oriented with an almost insatiable thirst for more information.
                </p>
            </article>
        </section>
        <footer>
            <h3>Download</h3>
            <dl>
                <dt>PDF</dt>
                <dd><a href="/resume/Resume-JoshuaRoss.pdf" title="My Resume" tabindex="<?php echo $tabIndex++; ?>">Resume-JoshuaRoss.pdf</a></dd>
                <dt>DOC</dt>
                <dd><a href="/resume/Resume-JoshuaRoss.doc" title="My Resume" tabindex="<?php echo $tabIndex++; ?>">Resume-JoshuaRoss.doc</a></dd>
            </dl>
        </footer>
    </body>
</html>
